name: chat
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - ca-certificates=2023.7.22=hbcca054_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - geos=3.11.0=h27087fc_0
  - ipython=7.33.0=py37h89c1867_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.9.0=18_linux64_openblas
  - libcblas=3.9.0=18_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libgomp=13.2.0=h807b86a_2
  - liblapack=3.9.0=18_linux64_openblas
  - libnsl=2.0.0=hd590300_1
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libsqlite=3.43.0=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libzlib=1.2.13=hd590300_5
  - line_profiler=3.4.0=py37h7cecad7_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - memory_profiler=0.61.0=pyhd8ed1ab_0
  - ncurses=6.4=hcb278e6_0
  - numpy=1.21.6=py37h976b520_0
  - openssl=3.1.3=hd590300_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.2.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - psutil=5.9.3=py37h540881e_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - python=3.7.12=hf930737_100_cpython
  - python_abi=3.7=4_cp37m
  - readline=8.2=h8228510_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - shapely=1.8.5=py37ha4e3bd1_0
  - sqlite=3.43.0=h2c6b66d_0
  - tk=8.6.13=h2797004_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - wcwidth=0.2.8=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - absl-py==2.0.0
    - aiohttp==3.7.4
    - allensdk==2.15.2
    - argschema==3.0.4
    - astor==0.8.1
    - async-timeout==3.0.1
    - attrs==23.1.0
    - boto3==1.17.21
    - botocore==1.20.112
    - cachetools==4.2.4
    - certifi==2023.7.22
    - chardet==3.0.4
    - charset-normalizer==3.3.0
    - cycler==0.11.0
    - deepslice==1.1.5
    - distro==1.8.0
    - future==0.18.3
    - gast==0.2.2
    - glymur==0.8.19
    - google-pasta==0.2.0
    - greenlet==3.0.0
    - grpcio==1.59.0
    - h5py==2.10.0
    - hdmf==3.4.7
    - idna==3.4
    - imageio==2.31.2
    - importlib-metadata==6.7.0
    - importlib-resources==5.12.0
    - jinja2==3.1.2
    - jmespath==0.10.0
    - joblib==1.3.2
    - jsonschema==4.17.3
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.5
    - lxml==4.9.3
    - markdown==3.4.4
    - markupsafe==2.1.3
    - marshmallow==3.19.0
    - matplotlib==3.4.2
    - multidict==6.0.4
    - ndx-events==0.2.0
    - nest-asyncio==1.5.8
    - networkx==2.6.3
    - numexpr==2.8.6
    - opt-einsum==3.3.0
    - packaging==23.2
    - pandas==1.3.5
    - patsy==0.5.3
    - pillow==9.5.0
    - pkgutil-resolve-name==1.3.10
    - protobuf==3.20.0
    - psycopg2-binary==2.9.9
    - pynrrd==0.4.3
    - pynwb==2.2.0
    - pyparsing==3.1.1
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - pywavelets==1.3.0
    - pyyaml==6.0.1
    - requests==2.31.0
    - requests-toolbelt==0.10.1
    - ruamel-yaml==0.17.35
    - ruamel-yaml-clib==0.2.8
    - s3transfer==0.3.7
    - scikit-build==0.17.6
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.12.2
    - semver==3.0.1
    - simpleitk==2.2.1
    - simplejson==3.19.1
    - six==1.16.0
    - sqlalchemy==2.0.21
    - statsmodels==0.13.5
    - tables==3.7.0
    - tensorboard==1.15.0
    - tensorflow==1.15.0
    - tensorflow-estimator==1.15.1
    - termcolor==2.3.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tomli==2.0.1
    - tqdm==4.66.1
    - typing==3.7.4.3
    - typing-extensions==4.7.1
    - urllib3==1.26.17
    - werkzeug==2.2.3
    - wrapt==1.15.0
    - xarray==0.20.2
    - yarl==1.9.2
    - zipp==3.15.0
prefix: /home/paul/src/miniconda3/envs/chat
